trigger:
  branches:
    include: [main, stage, qa, dev]

parameters:
- name: environment
  displayName: Target Environment
  type: string
  default: dev
  values: [dev, qa, stage, prod]

variables:
  dockerRegistryServiceConnection: 'e0af7d38-2ac5-4b5b-8988-aa364856ff89'
  imageRepository: 'lgexample654'
  containerRegistry: 'lgexample654.azurecr.io'
  tag: '$(Build.BuildId)'
  aksResourceGroup: 'terraform-prod'
  aksClusterName: 'demo-aks'
  helmReleaseName: 'lgexample'
  helmChartPath: 'helm/app'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: { vmImage: $(vmImageName) }
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to ${{ parameters.environment }}'
  dependsOn: Build
  jobs:
  - deployment: HelmDeploy
    environment: '${{ parameters.environment }}' # This enables Approval Gates in the UI
    pool: { vmImage: $(vmImageName) }
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Azure subscription 1(1)(525c7c1f-f5e9-4bf4-8d7a-5b7a06889a12)'
              azureResourceGroup: '$(aksResourceGroup)'
              kubernetesCluster: '$(aksClusterName)'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(helmChartPath)'
              releaseName: '$(helmReleaseName)'
              overrideValues: 'image.repository=$(containerRegistry)/$(imageRepository),image.tag=$(tag)'
              valueFile: '$(Build.SourcesDirectory)/$(helmChartPath)/values-${{ parameters.environment }}.yaml'
              arguments: '--atomic'